enforce documentation update in the pipeline

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,6 +28,43 @@ jobs:
       run: |
         go test -v -cover ./...
 
+  verifyDocs:
+    name: Verify docmentation
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    steps:
+      - name: Set up Go
+        uses: actions/setup-go@v2.1.3
+        with:
+          go-version: '1.17'
+        id: go
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v3
+
+      - name: Get dependencies
+        run: |
+          go mod download
+
+      - name: install tfplugindocs
+        run: |
+          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
+
+      - name: generate doc
+        run: |
+          go generate
+
+      # we will have changes if documentation were not generated. in this case the pipeline will fail.
+      - name: Changes validation
+        run: |
+          if [[ ! -z "$(git status --porcelain)" ]]
+          then
+            echo "terraform documentation has not been generated. please run:
+            go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
+            go generate"
+            exit 1
+          fi
+
   # run acceptance tests in a matrix with Terraform core versions
   test:
     name: Matrix Test
